[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node backend/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases]
setup = { nixPkgs = ["nodejs"] } 